# Cloud Run service definition
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: thumbnail-worker
  namespace: cloud-run-managed
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/plasma-galaxy-472907-c7/thumbnail-repo/thumbnail-worker:latest
          env:
            - name: BUCKET_NAME
              value: my-thumbnail-bucket
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
      serviceAccountName: thumbnail-worker-sa
---
# Eventarc trigger definition
apiVersion: eventarc.cnrm.cloud.google.com/v1beta1
kind: Trigger
metadata:
  name: gcs-to-thumbnail-worker
spec:
  location: us-central1
  matchingCriteria:
    - attribute: type
      value: google.cloud.storage.object.v1.finalized
    - attribute: bucket
      value: my-thumbnail-bucket
  serviceAccount: thumbnail-worker-sa@plasma-galaxy-472907-c7.iam.gserviceaccount.com
  destination:
    cloudRunService:
      service: thumbnail-worker
      region: us-central1
